<div class="eg">
            <div class="pic"> <img src="[field:litpic/]" width="180" height="135" id="img2" /> </div>
            <ul>
              <li>
                <h2 id="tit2">宠物托运-金毛</h2>
                <i id="des2">起始港：北京<br />
                目的港：澳大利亚悉尼<br />
                品 名：宠物狗</i>
                <p class="content" id="con2"> 发货人是一位母亲，孩 ...... </p>
                【<a href="[field:arcurl/]" target="_blank" id="detail2">查看详情</a>】 </li>
            </ul>
          </div>