<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	
<field:shr itemname="收货人" autofield="1" notsend="1" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:shr>
<field:sjg itemname="收件公司" autofield="1" notsend="1" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:sjg>
<field:ddr itemname="订单日期" autofield="1" notsend="1" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:ddr>
<field:sjr itemname="发件人" autofield="1" notsend="1" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:sjr>
<field:hwj itemname="货物价格" autofield="1" notsend="1" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:hwj>
<field:thr itemname="提货日期" autofield="1" notsend="1" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:thr>
<field:whm itemname="物货名称" autofield="1" notsend="1" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:whm>
<field:hyg itemname="货运公司" autofield="1" notsend="1" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:hyg>
<field:hyl itemname="货运类型" autofield="1" notsend="1" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:hyl>
<field:lxd itemname="联系电话" autofield="1" notsend="1" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:lxd>
<field:sjd itemname="收件地址" autofield="1" notsend="1" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:sjd>
<field:dqz itemname="当前状态" autofield="1" notsend="1" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:dqz>
<field:fhr itemname="发货人电话" autofield="1" notsend="1" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:fhr>
<field:hwy itemname="货物运费" autofield="1" notsend="1" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:hwy>
<field:hwz itemname="货物状态" autofield="1" notsend="1" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:hwz>
<field:hws itemname="货物数量" autofield="1" notsend="1" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:hws>
<field:zxd itemname="咨询电话" autofield="1" notsend="1" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:zxd>

<field:hwm itemname="货物明细" autofield="1" notsend="1" type="htmltext" isnull="true" islist="1" default=""  maxlength="text" page="">
</field:hwm>
