<div class="eg">
            <div class="pic"> <img src="[field:litpic/]" width="180" height="135" id="img1" /> </div>
            <ul>
              <li>
                <h2 id="tit1">宠物猫运输</h2>
                <i id="des1">起运港：上海<br  />
                目的港：新加坡<br  />
                品 种：英国短</i>
                <p class="content" id="con1"> 耳
                  Kitty，跟随主人 ...... </p>
                【<a href="[field:arcurl/]" target="_blank" id="detail1">查看详情</a>】 </li>
            </ul>
          </div>