<?php
$z[0]=Array("field","",220,239);
$z[0][4]['name']="title";
$z[1]=Array("global","",240,266);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",310,340);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",377,404);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("include","",1155,1194);
$z[4][4]['filename']="header_m.htm";
$z[5]=Array("field","",1477,1506);
$z[5][4]['name']="typename";
$z[6]=Array("channel","\r\n        <li><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"commonfont class-down\"></span></li>\r\n        ",1726,2053);
$z[6][4]['type']="son";
$z[6][4]['row']="10";
$z[6][4]['currentstyle']="<li class='hover'><a href='list.php?tid=~id~' ~rel~><span>~typename~</span></a> </li>";
$z[7]=Array("field","",2193,2212);
$z[7][4]['name']="title";
$z[8]=Array("field","",2261,2279);
$z[8][4]['name']="body";
$z[9]=Array("type"," <a href=\"list.php?tid=[field:id/]\" title=\"返回列表\" class=\"back\">返回列表</a>",2299,2400);
$z[10]=Array("include","",2444,2483);
$z[10][4]['filename']="footer_m.htm";

?>