<?php
$z[0]=Array("field","",314,333);
$z[0][4]['name']="title";
$z[1]=Array("global","",334,360);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",363,384);
$z[2][4]['name']="pagexx";
$z[3]=Array("field","",430,488);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("field","",525,554);
$z[4][4]['name']="keywords";
$z[5]=Array("include","",1276,1311);
$z[5][4]['filename']="head.htm";
$z[6]=Array("channel","\r\n            <LI><A href=\"[field:typeurl/]\">[field:typename/]</A> </LI>\r\n            ",1593,1739);
$z[6][4]['type']="son";
$z[6][4]['typeid']="7";
$z[6][4]['row']="10";
$z[7]=Array("list","\r\n                  <li><span class=\"STYLE1\"><a href=\"[field:arcurl/]\" class=\"title\">[field:title/] </a></span><span class=\"info\"><small>ÈÕÆÚ£º</small>[field:pubdate function=\"MyDate('y-m-d',@me)\"/] </span> </li>\r\n                  ",2763,3032);
$z[7][4]['pagesize']="10";
$z[8]=Array("pagelist","",3150,3216);
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",3464,3499);
$z[9][4]['filename']="foot.htm";

?>