<?php
$z[0]=Array("field","",314,336);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",337,363);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",407,465);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("field","",502,531);
$z[3][4]['name']="keywords";
$z[4]=Array("include","",1813,1848);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",2933,2968);
$z[5][4]['filename']="foot.htm";

?>