<?php
$z[0]=Array("field","",314,336);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",337,363);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",407,465);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("field","",502,531);
$z[3][4]['name']="keywords";
$z[4]=Array("include","",1088,1123);
$z[4][4]['filename']="head.htm";
$z[5]=Array("arclist","\r\n          <div class=\"eg\">\r\n            <div class=\"pic\"> <img src=\"[field:litpic/]\" width=\"180\" height=\"135\" id=\"img1\" /> </div>\r\n            <ul>\r\n              <li>\r\n                <h2 id=\"tit1\">宠物猫运输</h2>\r\n                <i id=\"des1\">起运港：上海<br  />\r\n                目的港：新加坡<br  />\r\n                品 种：英国短</i>\r\n                <p class=\"content\" id=\"con1\"> 耳\r\n                  Kitty，跟随主人 ...... </p>\r\n                【<a href=\"[field:arcurl/]\" target=\"_blank\" id=\"detail1\">查看详情</a>】 </li>\r\n            </ul>\r\n          </div>\r\n		  ",2436,3048);
$z[5][4]['row']="1";
$z[6]=Array("arclist","\r\n          <div class=\"eg\">\r\n            <div class=\"pic\"> <img src=\"[field:litpic/]\" width=\"180\" height=\"135\" id=\"img2\" /> </div>\r\n            <ul>\r\n              <li>\r\n                <h2 id=\"tit2\">宠物托运-金毛</h2>\r\n                <i id=\"des2\">起始港：北京<br />\r\n                目的港：澳大利亚悉尼<br />\r\n                品 名：宠物狗</i>\r\n                <p class=\"content\" id=\"con2\"> 发货人是一位母亲，孩 ...... </p>\r\n                【<a href=\"[field:arcurl/]\" target=\"_blank\" id=\"detail2\">查看详情</a>】 </li>\r\n            </ul>\r\n          </div>\r\n		   ",3054,3661);
$z[6][4]['limit']="1,1";
$z[7]=Array("include","",4555,4590);
$z[7][4]['filename']="foot.htm";

?>