<?php
$z[0]=Array("field","",314,333);
$z[0][4]['name']="title";
$z[1]=Array("global","",334,360);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field"," if(@me<>'' )@me = ''.@me.'';",404,495);
$z[2][4]['name']="description";
$z[2][4]['runphp']="yes";
$z[3]=Array("field","",532,554);
$z[3][4]['name']="keywords";
$z[4]=Array("include","",1963,1998);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",3275,3294);
$z[5][4]['name']="title";
$z[6]=Array("field","",7782,7800);
$z[6][4]['name']="body";
$z[7]=Array("include","",8727,8762);
$z[7][4]['filename']="foot.htm";

?>