<?php
$z[0]=Array("global","",368,390);
$z[0][4]['name']="cfg_tel";
$z[1]=Array("type","<a href=\" [field:typelink/]\" >[field:typename/]</a>",587,670);
$z[1][4]['typeid']="1";
$z[2]=Array("type","<a href=\" [field:typelink /]\" class=\"navlist03_menu01\"><span>[field:typename/]</span><i></i></a>",718,846);
$z[2][4]['typeid']="2";
$z[3]=Array("type","<a href=\" [field:typelink /]\" class=\"navlist03_menu02\"><span>[field:typename/]</span><i></i></a>",867,995);
$z[3][4]['typeid']="3";
$z[4]=Array("type","<a href=\" [field:typelink /]\" >[field:typename/]</a>",1040,1124);
$z[4][4]['typeid']="4";
$z[5]=Array("type","<a href=\" [field:typelink /]\" >[field:typename/]</a>",1141,1225);
$z[5][4]['typeid']="5";
$z[6]=Array("type","<a href=\"[field:typelink /]\" >[field:typename/]</a>",1242,1325);
$z[6][4]['typeid']="6";
$z[7]=Array("type","<a href=\"[field:typelink /]\" >[field:typename/]</a>",1342,1425);
$z[7][4]['typeid']="7";
$z[8]=Array("type","<a href=\" [field:typelink /]\" class=\"navlist05_menu02\"><span>[field:typename/]</span><i></i></a>",1473,1601);
$z[8][4]['typeid']="8";
$z[9]=Array("type","<a href=\" [field:typelink /]\" class=\"navlist05_menu06\"><span>[field:typename/]</span><i></i></a>",1712,1841);
$z[9][4]['typeid']="10";
$z[10]=Array("type","<a href=\" [field:typelink /]\" >[field:typename/]</a>",1886,1971);
$z[10][4]['typeid']="11";
$z[11]=Array("type","<a href=\" [field:typelink /]\" class=\"navlist06_menu01\"><span>[field:typename/]</span><i></i></a>",2019,2148);
$z[11][4]['typeid']="12";
$z[12]=Array("type","<a href=\" [field:typelink /]\" class=\"navlist06_menu02\"><span>[field:typename/]</span><i></i></a>",2169,2298);
$z[12][4]['typeid']="13";
$z[13]=Array("type"," <a href=\"[field:typelink /]\" class=\"navlist06_menu04\"><span>[field:typename/]</span><i></i></a>",2319,2448);
$z[13][4]['typeid']="14";

?>