<?php
$z[0]=Array("field","",314,336);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",337,363);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",407,465);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("field","",502,531);
$z[3][4]['name']="keywords";
$z[4]=Array("include","",1088,1123);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n      <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      ",1560,1807);
$z[5][4]['type']="son";
$z[5][4]['typeid']="2";
$z[5][4]['row']="10";
$z[5][4]['currentstyle']="<li><a href='~typelink~' title='~typename~' class='active'>~typename~</a> </li>";
$z[6]=Array("channel","\r\n      <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      ",2003,2250);
$z[6][4]['type']="son";
$z[6][4]['typeid']="3";
$z[6][4]['row']="10";
$z[6][4]['currentstyle']="<li><a href='~typelink~' title='~typename~' class='active'>~typename~</a> </li>";
$z[7]=Array("field","",3153,3175);
$z[7][4]['name']="typename";
$z[8]=Array("field","",3222,3243);
$z[8][4]['name']="content";
$z[9]=Array("include","",3345,3380);
$z[9][4]['filename']="foot.htm";

?>