<?php
$z[0]=Array("field","",314,333);
$z[0][4]['name']="title";
$z[1]=Array("global","",334,360);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",363,384);
$z[2][4]['name']="pagexx";
$z[3]=Array("field","",430,488);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("field","",525,554);
$z[4][4]['name']="keywords";
$z[5]=Array("include","",1325,1360);
$z[5][4]['filename']="head.htm";
$z[6]=Array("type"," [field:typelink /]",1652,1704);
$z[6][4]['typeid']="12";
$z[7]=Array("type"," [field:typelink /]",1769,1821);
$z[7][4]['typeid']="13";
$z[8]=Array("type"," [field:typelink /]",1869,1921);
$z[8][4]['typeid']="14";
$z[9]=Array("channel","  <A href=\"[field:typeurl/]\">[field:typename/]</A> ",2818,2930);
$z[9][4]['type']="son";
$z[9][4]['typeid']="13";
$z[9][4]['row']="10";
$z[10]=Array("list","\r\n				\r\n                  <li><span class=\"STYLE1\"><a href=\"[field:arcurl/]\" class=\"title\">[field:title/] </a></span><span class=\"info\"><small>ÈÕÆÚ£º</small>[field:pubdate function=\"MyDate('y-m-d',@me)\"/] </span>\r\n                 </li>\r\n				",3142,3421);
$z[10][4]['pagesize']="10";
$z[11]=Array("pagelist","",3553,3619);
$z[11][4]['listitem']="index,end,pre,next,pageno";
$z[11][4]['listsize']="5";
$z[12]=Array("include","",3866,3901);
$z[12][4]['filename']="foot.htm";

?>