<?php
$z[0]=Array("field","",220,239);
$z[0][4]['name']="title";
$z[1]=Array("global","",240,266);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",310,340);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",377,404);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("include","",1155,1194);
$z[4][4]['filename']="header_m.htm";
$z[5]=Array("field","",1477,1506);
$z[5][4]['name']="typename";
$z[6]=Array("channel","\r\n        <li><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"commonfont class-down\">¤f</span></li>\r\n        ",1726,2053);
$z[6][4]['type']="son";
$z[6][4]['row']="10";
$z[6][4]['currentstyle']="<li class='hover'><a href='list.php?tid=~id~' ~rel~><span>~typename~</span></a> </li>";
$z[7]=Array("list","\r\n      <li class=\"loop news2\"><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\"><span>[field:title/]</span><span>[field:pubdate function=\"MyDate('Y/m/d',@me)\"/]</span></a></li>\r\n      ",2221,2451);
$z[7][4]['pagesize']="8";
$z[8]=Array("pagelist","",2488,2554);
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",2598,2637);
$z[9][4]['filename']="footer_m.htm";

?>