<?php
$z[0]=Array("field","",314,333);
$z[0][4]['name']="title";
$z[1]=Array("global","",334,360);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field"," if(@me<>'' )@me = ''.@me.'';",404,495);
$z[2][4]['name']="description";
$z[2][4]['runphp']="yes";
$z[3]=Array("field","",532,554);
$z[3][4]['name']="keywords";
$z[4]=Array("include","",1197,1232);
$z[4][4]['filename']="head.htm";
$z[5]=Array("type"," [field:typelink /]",1523,1575);
$z[5][4]['typeid']="12";
$z[6]=Array("type"," [field:typelink /]",1640,1692);
$z[6][4]['typeid']="13";
$z[7]=Array("type"," [field:typelink /]",1740,1792);
$z[7][4]['typeid']="14";
$z[8]=Array("channel","  <A href=\"[field:typeurl/]\">[field:typename/]</A> ",2679,2791);
$z[8][4]['type']="son";
$z[8][4]['typeid']="13";
$z[8][4]['row']="10";
$z[9]=Array("field","",2886,2905);
$z[9][4]['name']="title";
$z[10]=Array("field","",3196,3248);
$z[10][4]['name']="pubdate";
$z[10][4]['function']="MyDate('Y-m-d',@me)";
$z[11]=Array("field","",3329,3347);
$z[11][4]['name']="body";
$z[12]=Array("include","",3564,3599);
$z[12][4]['filename']="foot.htm";

?>